apiVersion: v1
kind: Service
metadata:
  labels:
    name: podpincher
  name: podpincher
  namespace: default
spec:
  ports:
  - name: podpincher
    nodePort: 30977
    port: 4567
    protocol: TCP
    targetPort: 4567
  selector:
    name: podpincher
  sessionAffinity: None
  type: NodePort
